blog/urls.py
from django.urls import path
from . import views


app_name = 'blog'
urlpatterns = [
	path('', views.post_list, name='post_list'),
	path('<int:pk>/', views.post_detail, name='post_detail'),
	path('new/', views.post_new, name='post_new'),
	path('<int:pk>/edit', views.post_edit, name='post_edit'),
	path('drafts/', views.post_draft_list, name='post_draft_list'),
	path('post/<int:pk>/publish/', views.post_publish, name='post_publish'),
	path('post/<int:pk>/remove/', views.post_remove, name='post_remove'),
	path('post/<int:pk>/remove/drafts/', views.post_remove_draft, name='post_remove_draft'),
	path('signup/', views.signup, name='signup'),
	path('post/<int:pk>/comment/', views.add_comment_to_post, name='add_comment_to_post'),
	#path('post/<int:pk>/comment_to/', views.add_comment_to_comment, name='add_comment_to_comment'),
	path('post/<int:pk>/comment/remove/', views.comment_remove, name='comment_remove'),
	path('post/<int:pk>/comment/vote/', views.vote, name='vote'),
]

mblog/urls.py
from django.contrib import admin
from django.urls import path, include

from django.contrib.auth import views

urlpatterns = [
	path('blog/', include('blog.urls')),
	#path('', include('blog.urls')),
    path('admin/', admin.site.urls),
    path('login', views.LoginView.as_view(), name='login'),#name='login',定向login.html
    path('logout', views.LogoutView.as_view(), name='logout'),
]

blog/models.py
from django.db import models

# Create your models here.
from django.db import models
from django.utils import timezone


class Post(models.Model):
	author = models.ForeignKey('auth.User', on_delete=models.CASCADE)#关联auth.User表格
	title = models.CharField(max_length=200)
	text = models.TextField()
	created_date = models.DateTimeField(
		default=timezone.now)
	published_date = models.DateTimeField(
		blank=True, null=True)
	views = models.PositiveIntegerField(default=0)
	vote = models.PositiveIntegerField(default=0)

	def increase_views(self):#记录阅读量的方法,也可在视图写函数实现此功能
		self.views += 1 #访问文章即调用 Post 模型
		self.save(update_fields=['views'])#告诉数据库只更新views的值

	def publish(self):
		self.published_date = timezone.now()
		self.save()

	def __str__(self):
		return self.title

	def approved_comment(self):
		return self.comments.filter(approved_comment=True)


class Comment(models.Model):
	post = models.ForeignKey('blog.Post', on_delete=models.CASCADE, related_name='comments', default=True)#models.ForeignKey中的related_name选项允许我们在Post模型中连接 comments，即对应Post模型主键
	author2 = models.ForeignKey('auth.User', on_delete=models.CASCADE, default=True)
	author1 = models.CharField(max_length=200)
	talk = models.TextField()
	published_date1 = models.DateTimeField(
		default=timezone.now)

	def __str__(self):
		return self.talk

class Votes(models.Model):
	post = models.ForeignKey('blog.Post', on_delete=models.CASCADE, related_name='votes')
	author3 = models.ForeignKey('auth.User', on_delete=models.CASCADE)
	vote = models.PositiveIntegerField(default=0)
	status = models.BooleanField(default=True)
	published_date = models.DateTimeField(
		default=timezone.now)

	def __str__(self):
		return self.author3.username#不能返回一个对象

blog/forms.py
from django import forms

from .models import Post, Comment

class PostForm(forms.ModelForm):

	class Meta:
		model = Post
		fields = ('title', 'text',)


class Comment1Form(forms.ModelForm):

	class Meta:#告诉django哪个模型使用这个表单
		model = Comment
		fields = ('talk',)

			

blog/views.py
from django.shortcuts import render, get_object_or_404, redirect

# Create your views here.
from django.http import HttpResponse
from django.utils import timezone
from django.contrib.auth.decorators import login_required

from .models import Post, Comment, Votes
from .forms import PostForm, Comment1Form

#尝试
from django.contrib.auth import login, authenticate
from django.contrib.auth.forms import UserCreationForm

#-----------Queryset---------------------------------------------------------
#Queryset是model类对应的实例集合，即数据库对应表的子集，可称查询集
#------------POST------------------------------------------------------------

def post_list(request):
	posts = Post.objects.filter(published_date__lte=timezone.now())
	#print('fgsdfg',posts.objects.all())#会报错，posts是queryset而非对象
	for post in posts:
		vote2 = Votes.objects.filter(status=True, post=post.pk).count()#点赞量
		post.vote = vote2
		#print("123333333	",vote2)
		post.save(update_fields=['vote'])
	posts = Post.objects.filter(published_date__lte=timezone.now()).order_by('-vote')
	return render(request, 'blog/post_list.html', {'posts':posts})


'''
def post_list(request):#文章列表
	posts = Post.objects.filter(published_date__lte=timezone.now()).order_by('-views')# - 表示反排从大到小排序，
	return render(request, 'blog/post_list.html', {'posts':posts})
'''
def post_detail(request, pk):#内容详细页面，每打开一次post需要调用一次detail函数
	post = get_object_or_404(Post, pk=pk)#pk主键
	post.increase_views()#调用post模型中的increase_views函数记录阅读量
	vote1 = Votes.objects.filter(status=True,post=pk).count()#在一篇文章下的点赞数量
	status = Votes.objects.filter(post=pk, author3=request.user,status=True).count()
	#print('2132312',status)
	return render(request, 'blog/post_detail.html', {'post':post,'vote1':vote1,'status':status})#第三个参数为传递进模板的参数

@login_required
def post_new(request):#新建草稿并保存
	if request.method == "POST":
		form = PostForm(request.POST)
		if form.is_valid():
			post = form.save(commit=False)
			post.author = request.user
			#post.published_date = timezone.now()
			post.save()
			return redirect('blog:post_detail', pk=post.pk)
	else:
		form = PostForm()
	return render(request, 'blog/post_edit.html', {'form': form})

def post_edit(request, pk):#文章编辑功能。从urls里传递了一个额外的pk参数。
	post = get_object_or_404(Post, pk=pk)
	if request.method == 'POST':
		form = PostForm(request.POST, instance=post)#用实例来传递这篇文章
		if form.is_valid():
			post = form.save(commit=False)
			post.author = request.user
			post.published_date = timezone.now()
			post.save()
			return redirect('blog:post_detail', pk=post.pk)
	else:
		form = PostForm(instance=post)#当我们只是想打开文章编辑时
	return render(request, 'blog/post_edit.html', {'form': form})

@login_required
def post_draft_list(request):#草稿列表
	posts = Post.objects.filter(published_date__isnull=True).order_by('created_date')
	return render(request, 'blog/post_draft_list.html', {'posts': posts})

def post_publish(request, pk):#文章发布
	post = get_object_or_404(Post, pk=pk)
	post.publish()
	return redirect('blog:post_detail', pk=pk)

def publish(self):#发布时间
	self.published_date = timezone.now()
	self.save()

@login_required
def post_remove(request, pk):#删除文章
	post = get_object_or_404(Post, pk=pk)
	post.delete()
	return redirect('blog:post_list')

@login_required
def post_remove_draft(request, pk): #删除草稿
	post = get_object_or_404(Post, pk=pk)
	post.delete()
	return redirect('blog:post_draft_list')


#----------signup------------------------------------------------------------

def signup(request):#用户注册
	if request.method == 'POST':
		form = UserCreationForm(request.POST)
		if form.is_valid():
			form.save()
			username = form.cleaned_data.get('username')
			raw_password = form.cleaned_data.get('password1')
			user = authenticate(username=username, password=raw_password)
			login(request, user)
			return redirect('blog:post_list')
	else:
		form = UserCreationForm()
	return render(request, 'blog/signup.html', {'form':form})


#----------------comment---------------------------------------------

def add_comment_to_post(request, pk):#对文章增加评论
    post = get_object_or_404(Post, pk=pk)
    if request.method == "POST":
        form = Comment1Form(request.POST)
        if form.is_valid():
            comment = form.save(commit=False)
            comment.post = post#文章标题
            comment.author2 = request.user#请求的使用者设置为当前评论作者
            #print(comment.post)
            comment.save()
            return redirect('blog:post_detail', pk=post.pk)
    else:
        form = Comment1Form()
    return render(request, 'blog/add_comment_to_post.html', {'form': form})

@login_required
def comment_remove(request, pk):#删除评论
	comment = get_object_or_404(Comment,pk=pk)
	comment.delete()
	return redirect('blog:post_detail', pk=comment.post.pk)

#------点赞---------------------------------------------
def vote(request, pk):#文章点赞,pk为文章传入的即POST模型中的pk
	post1 = get_object_or_404(Post, pk=pk)#这是一个类
	#print("233333333333333",type(post1))
	#vote = post1.votes.all()
	if request.user.is_authenticated:#不要轻易删除数据库记录，对数据库性能影响较大
		#print("判断用户是否存在")
		vote1,c = post1.votes.get_or_create(author3=request.user, post=post1.pk,)#post=post1.pk与post=post1的区别.得到一个类
		#print("erterter",post1.votes.filter(author3=request.user, post=post1.pk,))
		#print("323452456",type(vote1))
		if c == True:
			#print("被创建")
			return redirect('blog:post_detail',pk=pk)
		elif c==False and vote1.status == True:
			#print("早就有了,变化消极状态")
			vote1.status = False
			vote1.save(update_fields=['status'])#修改一个字段
			return redirect('blog:post_detail', pk=pk)
		else:
			#print("早就有了，变化积极状态")
			vote1.status = True
			vote1.save(update_fields=['status'])
			return redirect('blog:post_detail', pk=pk)
			
	else:
		return redirect('blog:signup')

'''点赞的另一种实现
		vote1,c = post1.votes.get_or_create(author3=request.user, post=post1.pk,)#post=post1.pk与post=post1，区别
		if c == True:
			print("被创建")
			return redirect('blog:post_detail',pk=pk)
		else:
			print("早就有了")
			vote1.delete()
			return redirect('blog:post_detail', pk=pk)

'''	
"""
When you access user.details, it accesses the backreference of the UserDetail.user foreign key. The foreign Key itself doesn't specify that a 
User can only have one UserDetail, so django gives you a RelatedManager, which you can filter and query just like a regular Manager. So you do 
the same things to it that you do to your .objects managers. You can ask for user.details.all(), user.details.filter(), user.details.get(), and 
so on, which will either give you a queryset, an object, or an exception,depending on the method and the results.
"""

blog/templates/blog/add_comment_to_post.html
{% extends 'blog/base.html' %}

{% block content %}
    <h1>New comment</h1>
    <p> <strong>评论员：{{ comment.author2 }}</strong>此时没有post，暂不知user</p>
    <form method="POST" class="post-form">{% csrf_token %}
        {{ form.as_p }}
        <button type="submit" class="save btn btn-default">Send</button>
    </form>
{% endblock %}

blog/templates/blog/base.html
<!DOCTYPE html>
{% load static %}
<html>
<head>
<meta charset="utf-8">
	<title>SPIDER'S BLOG</title>

	<link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/bootstrap/3.2.0/css/bootstrap.min.css">
	<link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/bootstrap/3.2.0/css/bootstrap-theme.min.css">
	<link rel="stylesheet"  href="{%	static 'css/blog.css' %}">
</head>
<body>
	<div class='page-header'>


        {% if user.is_authenticated %}
		<a href="{% url 'blog:post_draft_list' %}" class="top-menu"><span class="glyphicon glyphicon-edit"></span></a>

		<a href="{% url 'blog:post_new' %}"	class="top-menu"><span	class="glyphicon	glyphicon-plus"></span></a>
		<p class="top-menu">Hello {{ user.username }} <small>(<a href="{% url 'logout' %}">Log out</a>)</small></p>
		{% else %}
            <a href="{% url 'login' %}" class="top-menu"><span class="glyphicon glyphicon-lock">login</span></a>
        {% endif %}


		<h1><a href="{% url 'blog:post_list' %}">Spider's blog</a></h1>
		<br/>
		<p class="name">十方</p>
	</div>
	<div class="content container">
		<div class="row">
			<div class="col-md-8">
		
				{% block content %}

				{% endblock %}
			
			</div>
		</div>
	</div>
	<p>本站作者为推送作者</p>
</body>
</html>

blog/templates/blog/post_detail.html
{% extends 'blog/base.html' %}

{% block content %}
		
		<div>
		<h2>{{ post.title }}</h2>
		<div><!--点赞-->
		
			{% if status == 0 %}
			<p>点赞{{ vote1 }}<a class="thumb1" href="{% url 'blog:vote' pk=post.pk %}"><span class="glyphicon glyphicon-thumbs-up"></span></a></p>
			{% else %}
			<p>点赞{{ vote1 }}<a class="thumb2" href="{% url 'blog:vote' pk=post.pk %}"><span class="glyphicon glyphicon-ok"></span></a></p>
			{% endif %}
		</div>
		<br/>

		<div class="post">
		{% if post.published_date %}<!--发布的post_list-->
			<div class="date">


				{% if post.author == request.user  %}

					{{ post.published_date}}
					<a href="{% url 'blog:post_remove' pk=post.pk %}">删除</a>
					<a	href="{%	url	'blog:post_edit'	pk=post.pk	%}">编辑</a>
					<br/>
				{% else %}
            	<a href="{% url 'login' %}" class="top-menu"><span class="glyphicon glyphicon-lock"></span></a>
        		{% endif %}
        		

		{% else %}<!--draft_list-->

				
				{% if post.author == request.user  %}
					<a href="{% url 'blog:post_publish' pk=post.pk %}" >Publish</a>
					<a href="{% url 'blog:post_remove_draft' pk=post.pk %}">删除</a>
				{% endif %}
			
			</div>
		{% endif %}
		</div>
		<p>作者：{{ post.author }}</p>
		<p>{{ post.text|linebreaksbr }}</p>
		</div>

		{% if user.is_authenticated and post.published_date %}<!--评论-->
        	<p> <a href="{% url 'blog:add_comment_to_post' pk=post.pk %}">comment</a></p>
        {% endif %}
		
		<hr/>

		{% for comment in post.comments.all %}
			{% if post.author == request.user or comment.author2 == request.user %}
			<div class="comment">
			    <div class="date">
			    {{ comment.published_date1 }}
			    <a  href="{% url 'blog:comment_remove' pk=comment.pk %}">删除</a>
				</div>
			</div>
            {% endif %}
			
			    <strong>评论员：{{ comment.author2 }}</strong>
			    <p>内容：{{ comment.talk|linebreaks }}</p>
			
				<hr/>
		    	
		{% empty %}
		    <p>No comments here yet :(</p>
		{% endfor %}

		

{% endblock %}

blog/templates/blog/post_draft_list.html
{% extends 'blog/base.html' %}

{% block content %}
    {% for post in posts %}
        <div class="post">
        	{% if post.author == request.user  %}
            <p>DRAFT LIST.</p>
            <p class="date"><a class="btn btn-default" href="{% url 'blog:post_remove_draft' pk=post.pk %}"><span class="glyphicon glyphicon-remove"></span></a> 保存日期: {{ post.created_date|date:'d-m-Y' }}</p>
            
            <h1><a href="{% url 'blog:post_detail' pk=post.pk %}">{{ post.title }}</a></h1>
            <p>作者：{{ post.author }}</p>
            <p>{{ post.text|truncatechars:200 }}</p>
            {% endif %}
        </div>
    {% endfor %}
{% endblock %}

blog/templates/blog/post_edit.html
{% extends 'blog/base.html' %}

{% block content %}
	<h1>New post</h1>
	<form method="POST" class="post-form">{% csrf_token %}
	{{ form.as_p }}
	<button type="submit" class="save btn btn-default">Save</button>
	</form>
{% endblock %}

blog/templates/blog/post_list.html
{% extends 'blog/base.html' %}



{% block content %}
	{% for post in posts %}
		<div class="post">
		<h2><a href="{% url 'blog:post_detail' pk=post.pk %}">{{post.title}}</a></h2>
			<div class="date">
				<p>发布日期: {{post.published_date}}</p>
			</div>
				<p>作者：{{post.author}}</p>
				<p>{{ post.text|truncatewords:"10" }}</p>
				<p><a href="{% url 'blog:post_detail' pk=post.pk %}">Comments: {{ post.comments.count }}  ; times: {{ post.views }} ; 喜爱人数: {{ post.vote }}</a></p>
		</div>
		
	{% endfor %}
{% endblock %}

blog/templates/blog/signup.html
{% extends 'blog/base.html' %}

{% block content %}
  <h2>Sign up</h2>
  <form method="post">
    {% csrf_token %}
    {% for field in form %}
      <p>
        {{ field.label_tag }}<br>
        {{ field }}
        {% if field.help_text %}
          <small style="color: grey">{{ field.help_text }}</small>
        {% endif %}
        {% for error in field.errors %}
          <p style="color: red">{{ error }}</p>
        {% endfor %}
      </p>
    {% endfor %}
    <button type="submit">Sign up</button>
  </form>
{% endblock %}